version: '0.2'

services:

  db-postgresql:
    image: vector_pt_br
    container_name: vector_postgres
    user: postgres
    command: postgres -c config_file=/etc/postgresql.conf
    #command: bash -c "sleep infinity"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 30
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
      POSTGRES_HOST_AUTH_METHOD: trust
    logging:
      options:
        max-size: 10m
        max-file: "3"
    network_mode: "host"
    ports:
      - '5432:5432'
    volumes:
      #- socks:/var/run/postgresql/:rw
      #- ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./postgresql.conf:/etc/postgresql.conf
      - ps_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1.5GB'
    # networks:
    #   - vector-network

  vector1: &vector
    build: .
    image: walmeidasantos/herecomesanewchallenger:latest
    hostname: vector1
    #command: "uvicorn main:app --loop uvloop --uds /tmp/vector1.sock --proxy-headers --no-access-log"
    command: "gunicorn main:app --bind unix:/tmp/vector1.sock "
    #command: bash -c "sleep infinity"
    network_mode: "host"
    environment:
      - ENV_NAME=vector
      - GUNICORN_WORKERS=2
      - GUNICORN_KEEPALIVE=4
      - TST=1
      - DB_URL=postgresql+asyncpg://postgres:postgres@127.0.0.1:5432/rinha
    # env_file:
    #   - .env
    depends_on:
      db-postgresql:
        condition: service_healthy
    volumes:
      - socks:/tmp
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.6GB'
    # ports:
    # - '8000:8000'
    # networks:
    #     - vector-network

  vector2:
    <<: *vector
    hostname: vector2
    #command: "uvicorn app:main --loop uvloop --uds /tmp/vector2.sock --proxy-headers --no-access-log"
    command: "gunicorn main:app --bind unix:/tmp/vector2.sock "
    depends_on:
      db-postgresql:
        condition: service_healthy
      vector1:
        condition: service_started
  nginx:
    image: nginx:latest
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - socks:/tmp
    depends_on:
      vector1:
        condition: service_started
      vector2:
        condition: service_started
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.3GB'
volumes:
  socks:
  ps_data:
